### ISSUE TITLE
\" is transformed into "

### ISSUE THREAD

**Issue by phenomen** [appurist/vscode-json-flattener#2]
Slash before double quotes (e.g `\"`) is removed during flattening.

**Comment by phenomen** [comment]
Also `\n` is removed and replaced by new string.

**Comment by appurist** [comment]
Ooh that's a good one. I'm surprised I didn't spot this myself or that it wasn't reported sooner, so thanks for that report!!!

I've fixed this in a [1.0.5 update](https://marketplace.visualstudio.com/items?itemName=Appurist.json-flattener) that is available now from within VS Code.
