### ISSUE TITLE
JavaScript array backets

### ISSUE THREAD

**Issue by tomByrer** [appurist/vscode-json-flattener#4]
Current output:
`formats.0.container`

JavaScript array items:
`formats[0].container`

Maybe best approach is to use default, & if `.#.` or `.#` at end, then transform via RegEx?
Still useful now, just requires extra editing ;)

**Comment by appurist** [comment]
This is a good point; FYI this is the format a colleague requested originally. I believe it matched other JSON flattener formats. 

So your last sentence leads to a question: what is the use case here? How are you using the resulting output? It sounds like it is input into a programming language of some kind?

**Comment by tomByrer** [comment]
Thanks for your fast reply!
Use case:
So I'm scraping data from a web site (which ends in Tube ;) ).  Fortunately much of the data I want is embedded in the webpage as JSON.  HUGE **JSON.  1Gb, 7000**+ entries.  Too big for a tree-view for me.

Flattening makes is very easy to manage & search of what object path I need.  I needed the data here:
```js
info.response.contents.twoColumnWatchNextResults.results.results.contents.1.videoSecondaryInfoRenderer.owner.videoOwnerRenderer.title.runs.0.navigationEndpoint.commandMetadata.webCommandMetadata.url
```
But JavaScript uses brackets for an array.  EG:
```js
const itemSecond = myArray[1]
```
You got me _very close_ to a simple copy/paste: my actual code is
```js
authorSlug = info.response.contents.twoColumnWatchNextResults.results.results.contents[1].videoSecondaryInfoRenderer.owner.videoOwnerRenderer.title.runs[0].navigationEndpoint.commandMetadata.webCommandMetadata.url
```

Note: the array item of an object has left bracket against the object name.  But a sub-object of an array item uses a dot after the right bracket.
```js
const subItem = myArray[1].subItem
```

I think I could create a RegEx or 2 to transform the output.  But either way, you'll need an internal API change.

**Comment by tomByrer** [comment]
Another option: add a new option to transform default 'dot' notation to JS.
This regex will work I think;
Named Capturing Groups:
qp = "0.
pp = .1.
pq = .2"

`/(?<qp>\"\d+\.)|(?<pp>\.\d+\.)|(?<pq>\.\d+\")/gm`

**Comment by tomByrer** [comment]
Maybe not RegEx; this works:
```js
	else if ((t === 'object') || isArray) {
		for (const k in obj) {
			if (obj.hasOwnProperty(k)) {
				if (isArray) {
					objToFlatArray(obj[k], acc, separator, `${prefix}[${k}]`);
				}
				else {
					let prefixDot = prefix ? prefix + separator : '';
					objToFlatArray(obj[k], acc, separator, `${prefixDot}${k}`);
				}
			}
		}
	}
```

But let me clean it up.

**Comment by tomByrer** [comment]
thanks!

**Comment by appurist** [comment]
@tomByrer It has now been [published on the VS Code Marketplace](https://marketplace.visualstudio.com/items?itemName=Appurist.json-flattener) as v1.1.0, thanks for the contribution!
